class ArtworkItem {
  final String id; // Thêm thuộc tính id
  final String title;
  final String artist;
  final String price;
  final String description; // Mô tả
  final String imagePath; //ảnh chính
  final String? material;
  final String? yearcreated; // Năm sáng tác (có thể để null nếu không có)
  final String? genre;
  final List<String> additionalImages; //danh sách ảnh phụ

  ArtworkItem({
    required this.id, // Thêm id vào constructor
    required this.title,
    required this.artist,
    required this.price,
    required this.description, // Mô tả
    required this.imagePath,
    required this.material,
    required this.genre,
    required this.yearcreated, // Năm sáng tác

    this.additionalImages = const [],
  });
  //getter lấy tất cả ảnh chính và phụ
  List<String> get allImages => [imagePath, ...additionalImages];
}

// Dữ liệu mẫu cho các tác phẩm nghệ thuật ở trang chủ
final List<ArtworkItem> homenewArtworks = [
  ArtworkItem(
    id: '1', // Thêm id cho mỗi item
    title: 'Flower in Oddy',
    artist: 'LT Nghiax',
    price: '100,000,000',
    material: '',
    yearcreated: '1970', // Năm sáng tác
    genre: 'Cổ điển',
    imagePath: 'assets/images/flowerstyle.jpg',
    description: '', // Mô tả mặc định là rỗng
  ),
    ArtworkItem(
    id: '2',
    title: 'Hoa Rừng',
    artist: 'Dain',
    yearcreated: '2020',
    genre: 'Hoa',
    price: '123,078,000',
    description: 'Vẻ đẹp thời đại của khoản khắt.',
    imagePath: 'assets/images/bh2.jpg',
    material: '',
  ),
    ArtworkItem(
    id: '3',
    title: 'Tĩnh lặng dưới hoa',
    artist: 'Võ Huy',
    yearcreated: '2019',
    genre: 'Hoa',
    price: '5,000.000',
    description: 'Bức tranh khắc họa khoảnh khắc yên bình nơi một góc sân cổ, nơi dây tử đằng tím rũ rượi giữa ánh nắng sớm mai, những cánh chim bồ câu nhẹ nhàng bay lượn như gợi về ký ức một thời thanh xuân dịu dàng. Không gian nhẹ nhàng, thơ mộng mang lại cảm giác tĩnh tại và hoài cổ.',
    imagePath: 'assets/images/bc1.jpg',
    material: 'Sơn dầu trên toan',
  ),  ArtworkItem(
    id: '4',
    title: 'Cuồng phong trên miền xanh',
    artist: 'Kha Trần',
    yearcreated: '2022',
    genre: 'Bối cảnh',
    price: '120,500,000',
    description: 'Bức tranh tái hiện một khung cảnh thiên nhiên kỳ vĩ với bầu trời cuộn xoáy dữ dội như những cơn giông gào thét. Trên nền đất thanh bình, con người hiện lên nhỏ bé giữa đại ngàn vũ trụ. Màu sắc rực rỡ và tương phản mạnh mẽ mang lại cảm giác vừa hùng tráng vừa thi vị, như một cuộc đối thoại giữa đất và trời, giữa bình yên và hỗn loạn.',
    imagePath: 'assets/images/bc2.jpg',
    material: 'Sơn dầu trên toan',
  ),  ArtworkItem(
    id: '5',
    title: 'Lặng giữa đầm xanh',
    artist: 'Vũ Nguyễn',
    yearcreated: '2015',
    genre: 'Bối cảnh',
    price: '54,000,000',
    description: 'Bức tranh khắc họa một góc đầm sen hoang sơ rợp bóng cây, nơi ánh sáng mùa hạ len lỏi qua từng tán lá, phản chiếu lên mặt nước lặng như gương. Sự phối màu sống động và lối vẽ đậm chất ấn tượng tạo nên một không gian yên bình, thơ mộng và rất đỗi trữ tình – như một bản hòa ca của thiên nhiên và tĩnh lặng.',
    imagePath: 'assets/images/bc3.jpg',
    material: 'Sơn dầu trên toan',
  ),  ArtworkItem(
    id: '6',
    title: 'Sớm mai bên khung cửa',
    artist: 'Duy Nguyễn',
    yearcreated: '1998',
    genre: 'Bối cảnh',
    price: '75,078,000',
    description: 'Bức tranh ghi lại khoảnh khắc tươi sáng của buổi sớm mùa xuân, khi khung cửa sổ mở toang đón ánh nắng chan hòa. Những cánh hoa hồng rơi rụng trên sàn gỗ cũ kỹ, gió khẽ lay rèm trắng và cây xanh bên ngoài như mời gọi một ngày mới. Không gian trong tranh vừa giản dị, vừa đầy thi vị – như một đoạn thơ thả nhẹ vào đời thường.',
    imagePath: 'assets/images/bc4.jpg',
    material: 'Sơn dầu trên toan',
  ),  ArtworkItem(
    id: '7',
    title: 'Ánh nhìn lặng thinh',
    artist: 'IYuo',
    yearcreated: '2021',
    genre: 'Chân dung',
    price: '115,618,000',
    description: 'Bức chân dung khắc họa vẻ đẹp tinh tế và đầy cảm xúc của một người con gái trẻ. Từng đường cọ được xử lý mượt mà, thể hiện làn da ửng hồng, đôi mắt sâu lắng và thần thái vừa dịu dàng vừa mạnh mẽ. Nền đỏ trầm làm nổi bật nhân vật chính, tạo cảm giác như cô đang bước ra từ khung tranh với một câu chuyện chưa kể.',
    imagePath: 'assets/images/cd1.jpg',
    material: 'Sơn dầu trên toan',
  ),
  ArtworkItem(
    id: '8',
    title: 'Ánh sáng từ bên trong',
    artist: 'Tịnh Phong',
    yearcreated: '2024',
    genre: 'Chân dung',
    price: '23,000,000',
    description: 'Bức chân dung ghi lại khoảnh khắc người thiếu nữ đắm mình trong luồng ánh sáng ấm áp, tựa như thể ánh sáng phát ra từ chính nội tâm cô. Sự mềm mại trong nét vẽ, sự hoà quyện giữa tông da và ánh sáng, cùng ánh mắt thoáng buồn đã tạo nên một tác phẩm chân dung mang chiều sâu tâm lý và chất trữ tình khó diễn tả.',
    imagePath: 'assets/images/cd2.jpg',
    material: 'Sơn dầu trên toan',
  ),
  ArtworkItem(
    id: '9',
    title: 'Giữ lấy ánh sáng',
    artist: 'Noctune',
    yearcreated: '2014',
    genre: 'Chân dung',
    price: '3,600,000',
    description: 'Người thiếu nữ trong tranh đang khép mắt, tay nâng nhẹ ngọn nến như một nghi lễ thiêng liêng. Ánh sáng nhỏ bé của cây nến soi rọi khuôn mặt cô, làm nổi bật vẻ đẹp mong manh, đồng thời gợi cảm giác nội tâm sâu lắng. Tác phẩm khai thác xuất sắc tương phản giữa ánh sáng và bóng tối, làm nổi bật chiều sâu tâm hồn con người trong khoảnh khắc suy niệm.',
    imagePath: 'assets/images/cd3.jpg',
    material: 'Sơn dầu trên vải lanh',
  ),
  ArtworkItem(
    id: '10',
    title: 'Buổi sáng trong khu vườn',
    artist: 'Huyzen',
    yearcreated: '2017',
    genre: 'Cổ điển',
    price: '18,618,000',
    description: 'Một thiếu nữ đang ngồi đọc sách trong khu vườn rực rỡ sắc hoa, ánh nắng nhẹ xuyên qua tán lá tạo nên không gian huyền ảo, thanh bình. Bức tranh là bản hòa tấu của thiên nhiên, ánh sáng và con người – nơi mà sự yên tĩnh của tâm hồn được thả trôi giữa hương thơm cỏ hoa và tiếng gió khe khẽ lay động.',
    imagePath: 'assets/images/codien1.jpg',
    material: 'Sơn dầu trên vải bố',
  ),
  ArtworkItem(
    id: '11',
    title: 'Cô gái bên cửa sổ',
    artist: 'aspar David Friedrich',
    yearcreated: '1970',
    genre: 'Cổ điển',
    price: '40,618,000',
    description: 'Bức tranh thể hiện hình ảnh cô gái đứng bên cửa sổ, ánh sáng dịu nhẹ chiếu vào tạo không khí yên bình và mơ mộng. Cô gái với vẻ đẹp thanh thoát, đôi mắt nhìn xa xăm như đang suy tư về cuộc sống. Nền cảnh vật bên ngoài cửa sổ là những cánh đồng xanh mướt, tạo nên một bức tranh hài hòa giữa con người và thiên nhiên.',
    imagePath: 'assets/images/codien2.jpg',
    material: 'Sơn dầu trên vải bố',
  ),
  ArtworkItem(
    id: '12',
    title: 'Chân dung tự họa với người chơi violin',
    artist: 'Édouard Manet',
    yearcreated: 'Cuối thế kỷ 19',
    genre: 'Cổ điển',
    price: '17,051,000',
    description: 'Chân dung họa sĩ đang cầm cọ vẽ, phía sau là người chơi violin, tạo cảm giác nghệ thuật và sâu lắng.',
    imagePath: 'assets/images/codien3.jpg',
    material: 'Sơn dầu trên vải',
  ),
    ArtworkItem(
    id: '13',
    title: 'Chân dung người đàn ông',
    artist: 'Maurice Denis',
    yearcreated: '2010',
    genre: 'Hiện đại',
    price: '22,000,000',
    description: 'Chân dung người đàn ông mặc vest, ngồi nghiêng người, thể hiện sự suy tư và tĩnh lặng.',
    imagePath: 'assets/images/md1.jpg',
    material: 'Sơn dầu trên vải',
  ),
    ArtworkItem(
    id: '14',
    title: 'Cuộc sống bên cửa sổ',
    artist: 'Nhiều tác giả',
    yearcreated: '2022',
    genre: 'Hiện đại',
    price: '13,000,000',
    description: 'Bộ ảnh tổng hợp nhiều khung cửa sổ với các cảnh sinh hoạt, giao tiếp và khoảnh khắc đời thường khác nhau.',
    imagePath: 'assets/images/md2.jpg',
    material: '',
  ),
];

// Dữ liệu mẫu cho các tác phẩm nghệ thuật
final List<ArtworkItem> newArtworks = [
  ArtworkItem(
      id: '15',
      title: 'Flower in Oddy',
      artist: 'LT Nghiax',
      price: '100,000,000',
      description:
          'Từ sâu thẳm khu rừng, một bản giao hưởng sắc màu hiện lên, là khúc ca rực rỡ của những loài hoa dại được vẽ nên bằng nét chạm tinh tế. Mỗi đóa hoa như một kiệt tác thu nhỏ, bừng nở sức sống, cánh hoa nhẹ nhàng bung nở tựa đôi cánh lụa mỏng.',
      imagePath: 'assets/images/flowerstyle.jpg',
      genre: 'Cổ điển',
      material: 'Acrylic',
      yearcreated: '1970',
      additionalImages: [
        'assets/images/bh1.jpg',
        'assets/images/bh2.jpg',
      ]),
  ArtworkItem(
    id: '16',
    title: 'Hoa Rừng',
    artist: 'Dain',
    yearcreated: '2020',
    genre: 'Hoa',
    price: '123,078,000',
    description: 'Vẻ đẹp thời đại của khoản khắt.',
    imagePath: 'assets/images/bh2.jpg',
    material: '',
  ),
  ArtworkItem(
    id: '17',
    title: 'Tĩnh lặng dưới hoa',
    artist: 'Võ Huy',
    yearcreated: '2019',
    genre: 'Hoa',
    price: '5,000.000',
    description: 'Bức tranh khắc họa khoảnh khắc yên bình nơi một góc sân cổ, nơi dây tử đằng tím rũ rượi giữa ánh nắng sớm mai, những cánh chim bồ câu nhẹ nhàng bay lượn như gợi về ký ức một thời thanh xuân dịu dàng. Không gian nhẹ nhàng, thơ mộng mang lại cảm giác tĩnh tại và hoài cổ.',
    imagePath: 'assets/images/bc1.jpg',
    material: 'Sơn dầu trên toan',
  ),  ArtworkItem(
    id: '18',
    title: 'Cuồng phong trên miền xanh',
    artist: 'Kha Trần',
    yearcreated: '2022',
    genre: 'Bối cảnh',
    price: '120,500,000',
    description: 'Bức tranh tái hiện một khung cảnh thiên nhiên kỳ vĩ với bầu trời cuộn xoáy dữ dội như những cơn giông gào thét. Trên nền đất thanh bình, con người hiện lên nhỏ bé giữa đại ngàn vũ trụ. Màu sắc rực rỡ và tương phản mạnh mẽ mang lại cảm giác vừa hùng tráng vừa thi vị, như một cuộc đối thoại giữa đất và trời, giữa bình yên và hỗn loạn.',
    imagePath: 'assets/images/bc2.jpg',
    material: 'Sơn dầu trên toan',
  ),  ArtworkItem(
    id: '19',
    title: 'Lặng giữa đầm xanh',
    artist: 'Vũ Nguyễn',
    yearcreated: '2015',
    genre: 'Bối cảnh',
    price: '54,000,000',
    description: 'Bức tranh khắc họa một góc đầm sen hoang sơ rợp bóng cây, nơi ánh sáng mùa hạ len lỏi qua từng tán lá, phản chiếu lên mặt nước lặng như gương. Sự phối màu sống động và lối vẽ đậm chất ấn tượng tạo nên một không gian yên bình, thơ mộng và rất đỗi trữ tình – như một bản hòa ca của thiên nhiên và tĩnh lặng.',
    imagePath: 'assets/images/bc3.jpg',
    material: 'Sơn dầu trên toan',
  ),  ArtworkItem(
    id: '20',
    title: 'Sớm mai bên khung cửa',
    artist: 'Duy Nguyễn',
    yearcreated: '1998',
    genre: 'Bối cảnh',
    price: '75,078,000',
    description: 'Bức tranh ghi lại khoảnh khắc tươi sáng của buổi sớm mùa xuân, khi khung cửa sổ mở toang đón ánh nắng chan hòa. Những cánh hoa hồng rơi rụng trên sàn gỗ cũ kỹ, gió khẽ lay rèm trắng và cây xanh bên ngoài như mời gọi một ngày mới. Không gian trong tranh vừa giản dị, vừa đầy thi vị – như một đoạn thơ thả nhẹ vào đời thường.',
    imagePath: 'assets/images/bc4.jpg',
    material: 'Sơn dầu trên toan',
  ),  ArtworkItem(
    id: '21',
    title: 'Ánh nhìn lặng thinh',
    artist: 'IYuo',
    yearcreated: '2021',
    genre: 'Chân dung',
    price: '115,618,000',
    description: 'Bức chân dung khắc họa vẻ đẹp tinh tế và đầy cảm xúc của một người con gái trẻ. Từng đường cọ được xử lý mượt mà, thể hiện làn da ửng hồng, đôi mắt sâu lắng và thần thái vừa dịu dàng vừa mạnh mẽ. Nền đỏ trầm làm nổi bật nhân vật chính, tạo cảm giác như cô đang bước ra từ khung tranh với một câu chuyện chưa kể.',
    imagePath: 'assets/images/cd1.jpg',
    material: 'Sơn dầu trên toan',
  ),
  ArtworkItem(
    id: '22',
    title: 'Ánh sáng từ bên trong',
    artist: 'Tịnh Phong',
    yearcreated: '2024',
    genre: 'Chân dung',
    price: '23,000,000',
    description: 'Bức chân dung ghi lại khoảnh khắc người thiếu nữ đắm mình trong luồng ánh sáng ấm áp, tựa như thể ánh sáng phát ra từ chính nội tâm cô. Sự mềm mại trong nét vẽ, sự hoà quyện giữa tông da và ánh sáng, cùng ánh mắt thoáng buồn đã tạo nên một tác phẩm chân dung mang chiều sâu tâm lý và chất trữ tình khó diễn tả.',
    imagePath: 'assets/images/cd2.jpg',
    material: 'Sơn dầu trên toan',
  ),
  ArtworkItem(
    id: '23',
    title: 'Giữ lấy ánh sáng',
    artist: 'Noctune',
    yearcreated: '2014',
    genre: 'Chân dung',
    price: '3,600,000',
    description: 'Người thiếu nữ trong tranh đang khép mắt, tay nâng nhẹ ngọn nến như một nghi lễ thiêng liêng. Ánh sáng nhỏ bé của cây nến soi rọi khuôn mặt cô, làm nổi bật vẻ đẹp mong manh, đồng thời gợi cảm giác nội tâm sâu lắng. Tác phẩm khai thác xuất sắc tương phản giữa ánh sáng và bóng tối, làm nổi bật chiều sâu tâm hồn con người trong khoảnh khắc suy niệm.',
    imagePath: 'assets/images/cd3.jpg',
    material: 'Sơn dầu trên vải lanh',
  ),
  ArtworkItem(
    id: '24',
    title: 'Buổi sáng trong khu vườn',
    artist: 'Huyzen',
    yearcreated: '2017',
    genre: 'Cổ điển',
    price: '18,618,000',
    description: 'Một thiếu nữ đang ngồi đọc sách trong khu vườn rực rỡ sắc hoa, ánh nắng nhẹ xuyên qua tán lá tạo nên không gian huyền ảo, thanh bình. Bức tranh là bản hòa tấu của thiên nhiên, ánh sáng và con người – nơi mà sự yên tĩnh của tâm hồn được thả trôi giữa hương thơm cỏ hoa và tiếng gió khe khẽ lay động.',
    imagePath: 'assets/images/codien1.jpg',
    material: 'Sơn dầu trên vải bố',
  ),
  ArtworkItem(
    id: '25',
    title: 'Cô gái bên cửa sổ',
    artist: 'aspar David Friedrich',
    yearcreated: '1970',
    genre: 'Cổ điển',
    price: '40,618,000',
    description: 'Bức tranh thể hiện hình ảnh cô gái đứng bên cửa sổ, ánh sáng dịu nhẹ chiếu vào tạo không khí yên bình và mơ mộng. Cô gái với vẻ đẹp thanh thoát, đôi mắt nhìn xa xăm như đang suy tư về cuộc sống. Nền cảnh vật bên ngoài cửa sổ là những cánh đồng xanh mướt, tạo nên một bức tranh hài hòa giữa con người và thiên nhiên.',
    imagePath: 'assets/images/codien2.jpg',
    material: 'Sơn dầu trên vải bố',
  ),
  ArtworkItem(
    id: '26',
    title: 'Chân dung tự họa với người chơi violin',
    artist: 'Édouard Manet',
    yearcreated: 'Cuối thế kỷ 19',
    genre: 'Cổ điển',
    price: '17,051,000',
    description: 'Chân dung họa sĩ đang cầm cọ vẽ, phía sau là người chơi violin, tạo cảm giác nghệ thuật và sâu lắng.',
    imagePath: 'assets/images/codien3.jpg',
    material: 'Sơn dầu trên vải',
  ),
    ArtworkItem(
    id: '27',
    title: 'Chân dung người đàn ông',
    artist: 'Maurice Denis',
    yearcreated: '2010',
    genre: 'Hiện đại',
    price: '22,000,000',
    description: 'Chân dung người đàn ông mặc vest, ngồi nghiêng người, thể hiện sự suy tư và tĩnh lặng.',
    imagePath: 'assets/images/md1.jpg',
    material: 'Sơn dầu trên vải',
  ),
    ArtworkItem(
    id: '28',
    title: 'Cuộc sống bên cửa sổ',
    artist: 'Nhiều tác giả',
    yearcreated: '2022',
    genre: 'Hiện đại',
    price: '13,000,000',
    description: 'Bộ ảnh tổng hợp nhiều khung cửa sổ với các cảnh sinh hoạt, giao tiếp và khoảnh khắc đời thường khác nhau.',
    imagePath: 'assets/images/md2.jpg',
    material: '',
  ),


];
//dữ liệu tác phẩm đấu giá
final List<ArtworkItem> DauGiaTP = [
  ArtworkItem(
      id: '1',
      title: 'Vạm Thiên',
      artist: 'NghiaLT',
      price: '129,000,000',
      description: 'Tác phẩm nghệ thuật đương đại',
      imagePath: 'assets/images/vam_thien.png',
      material: 'Sơn dầu trên canvas',
      genre: 'Phong cảnh',
      yearcreated: '2004'),
  ArtworkItem(
      id: '2',
      title: 'Hoàng Hôn',
      artist: 'TranABC',
      price: '85,000,000',
      description: 'Bức tranh phong cảnh tuyệt đẹp',
      imagePath: 'assets/images/vam_thien.png',
      material: 'Acrylic',
      genre: 'Phong cảnh',
      yearcreated: '2010'),
];
